version: "2"
services:
    app:
        build: .
        image: cloud-native-go:1.0.1-alpine
        environment:
        - PORT=9090
        ports:
        - "9090:9090"
    reverse-proxy:
        image: nginx:1.16-alpine
        ports:
        - "8080:80"
        links:
        - app